defaults: &defaults
  app_name: Hipscan
  from_email: support@hipscan.com
  base_domain: hipscan.com
  gateway: authorize_net_cim
  require_payment_info_for_trials: false
  credentials:
    gateway:
      :login: buzzsocial1
      :password: Moorcheh1
      # :test: true
    paypal:
      :login: info_api1.hipscan.com
      :password: ZXV6JAU2NYTMMB6L
      :signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AA3w8uCFhKqLSLgvagrD347wp9t4
    
development:
  <<: *defaults
  base_domain: subscriptions.dev # Edit /etc/hosts to add subscriptions.dev, test.subscriptions.dev, etc., or use Pow: http://pow.cx
  require_payment_info_for_trials: false
  gateway: authorize_net_cim
  # credentials:
  #   gateway:
  #     :login: 7MaS7yD7hL
  #     :password: 76Cf4WHc4S7J9c93
  #   paypal:
  #     :login: demo
  #     :password: password
  #     :signature: signature

test:
  <<: *defaults
  
staging:
  <<: *defaults

production:
  <<: *defaults