--- 
carriers: 
  aliant-canada: 
    name: "Aliant (Canada)"
    value: "@chat.wirefree.ca"
  alltel: 
    name: Alltel
    value: "@message.alltel.com"
  ameritech: 
    name: Ameritech
    value: "@paging.acswireless.com"
  at&t: 
    name: AT&T
    value: "@txt.att.net"
  beeline-ua: 
    name: Beeline
    value: "@sms.beeline.ua"
  bell-atlantic: 
    name: "Bell Atlantic"
    value: "@message.bam.com"
  bellmobility-canada: 
    name: "Bell Mobility (Canada)"
    value: "@txt.bell.ca"
  bellsouthmobility: 
    name: "Bellsouth Mobility"
    value: "@blsdcs.net"
  blueskyfrog: 
    name: BlueSkyFrog
    value: "@blueskyfrog.com"
  boost: 
    name: "Boost Mobile"
    value: "@myboostmobile.com"
  bpl-mobile: 
    name: "BPL Mobile"
    value: "@bplmobile.com"
  cellularsouth: 
    name: "Cellular South"
    value: "@csouth1.com"
  claro-brazil: 
    name: "Claro (Brazil)"
    value: "@clarotorpedo.com.br"
  claro-nicaragua: 
    name: "Claro (Nicaragua)"
    value: "@ideasclaro-ca.com"
  comcast: 
    name: "Comcast PCS"
    value: "@comcastpcs.textmsg.com"
  cricket: 
    name: Cricket
    value: "@sms.mycricket.com"
  du-arab-emirates: 
    name: "Du (UAE)"
    value: "@email2sms.ae"
  e-plus-germany: 
    name: "E-Plus (Germany)"
    value: "@smsmail.eplus.de"
  etisalat-arab-emirates: 
    name: "Etisalat (UAE)"
    value: "@email2sms.ae"
  fido-canada: 
    name: Fido
    value: "@fido.ca"
  kajeet: 
    name: kajeet
    value: "@mobile.kajeet.net"
  manitobatelecom-canada: 
    name: "Manitoba Telecom (Canada)"
    value: "@text.mtsmobility.com"
  metropcs: 
    name: "Metro PCS"
    value: "@mymetropcs.com"
  mobinil-egypt: 
    name: Mobinil
    value: "@mobinil.net"
  mobistar-belgium: 
    name: "Mobistar (Belgium)"
    value: "@mobistar.be"
  mobitel: 
    name: Mobitel
    value: "@sms.mobitel.lk"
  movistar-spain: 
    name: "Movistar (Spain)"
    value: "@correo.movistar.net"
  nextel: 
    name: Nextel
    value: "@messaging.nextel.com"
  northerntel-canada: 
    name: "NorthernTel (Canada)"
    value: "@txt.northerntelmobility.com"
  o2-germany: 
    name: "o2 (Germany)"
    value: "@o2online.de"
  o2-uk: 
    name: "o2 (UK)"
    value: "@mmail.co.uk"
  orange-mumbai: 
    name: "Orange (Mumbai)"
    value: "@orangemail.co.in"
  orange-netherlands: 
    name: "Orange (Netherlands)"
    value: "@sms.orange.nl"
  orange-uk: 
    name: "Orange (UK)"
    value: "@orange.net"
  powertel: 
    name: Powertel
    value: "@ptel.net"
  pscwireless: 
    name: "PSC Wireless"
    value: "@sms.pscel.com"
  qwest: 
    name: Qwest
    value: "@qwestmp.com"
  rogers-canada: 
    name: "Rogers (Canada)"
    value: "@pcs.rogers.ca"
  rogers-wireless: 
    name: "Rogers Wireless"
    value: "@pcs.rogers.com"
  sasktel-canada: 
    name: "SaskTel (canada)"
    value: "@sms.sasktel.ca"
  sfr-france: 
    name: "SFR (France)"
    value: "@sfr.fr"
  southernlink: 
    name: "Southern Link"
    value: "@page.southernlinc.com"
  sprint: 
    name: "Sprint PCS"
    value: "@messaging.sprintpcs.com"
  suncom: 
    name: Suncom
    value: "@tms.suncom.com"
  t-mobile: 
    name: T-Mobile
    value: "@tmomail.net"
  t-mobile-austria: 
    name: "T-Mobile (Austria)"
    value: "@sms.t-mobile.at"
  t-mobile-germany: 
    name: "T-Mobile (Netherlands)"
    value: "@gin.nl"
  t-mobile-uk: 
    name: "T-Mobile (UK)"
    value: "@t-mobile.uk.net"
  telebec-canada: 
    name: "Telebec (Canada)"
    value: "@txt.telebecmobilite.com"
  telefonica-spain: 
    name: "Telefonica (Spain)"
    value: "@movistar.net"
  telus-canada: 
    name: "Telus (Canada)"
    value: "@msg.telus.com"
  telus-mobility: 
    name: "Telus Mobility"
    value: "@msg.telus.com"
  tracfone: 
    name: Tracfone
    value: "@mmst5.tracfone.com"
  verizon: 
    name: "Verizon Wireless"
    value: "@vtext.com"
  virgin: 
    name: "Virgin Mobile"
    value: "@vmobl.net"
  virgin-canada: 
    name: "Virgin (Canada)"
    value: "@vmobile.ca"
  vodafone-egypt: 
    name: "Vodafone (Egypt)"
    value: "@vodafone.com.eg"
  vodafone-germany: 
    name: "Vodafone (Germany)"
    value: "@vodafone-sms.de"
  vodafone-italy: 
    name: "Vodafone (Italy)"
    value: "@sms.vodafone.it"
  vodafone-jp-chuugoku: 
    name: "Vodafone (Japan - Chuugoku)"
    value: "@n.vodafone.ne.jp"
  vodafone-jp-hokkaido: 
    name: "Vodafone (Japan - Hokkaido)"
    value: "@d.vodafone.ne.jp"
  vodafone-jp-hokuriko: 
    name: "Vodafone (Japan - Hokuriko)"
    value: "@r.vodafone.ne.jp"
  vodafone-jp-kansai: 
    name: "Vodafone (Japan - Kansai)"
    value: "@k.vodafone.ne.jp"
  vodafone-jp-kanto: 
    name: "Vodafone (Japan - Kanto)"
    value: "@k.vodafone.ne.jp"
  vodafone-jp-koushin: 
    name: "Vodafone (Japan - Koushin)"
    value: "@k.vodafone.ne.jp"
  vodafone-jp-kyuushu: 
    name: "Vodafone (Japan - Kyuushu)"
    value: "@q.vodafone.ne.jp"
  vodafone-jp-niigata: 
    name: "Vodafone (Japan - Niigata)"
    value: "@h.vodafone.ne.jp"
  vodafone-jp-okinawa: 
    name: "Vodafone (Japan - Okinawa)"
    value: "@q.vodafone.ne.jp"
  vodafone-jp-osaka: 
    name: "Vodafone (Japan - Osaka)"
    value: "@k.vodafone.ne.jp"
  vodafone-jp-shikoku: 
    name: "Vodafone (Japan - Shikoku)"
    value: "@s.vodafone.ne.jp"
  vodafone-jp-tokyo: 
    name: "Vodafone (Japan - Tokyo)"
    value: "@k.vodafone.ne.jp"
  vodafone-jp-touhoku: 
    name: "Vodafone (Japan - Touhoku)"
    value: "@h.vodafone.ne.jp"
  vodafone-jp-toukai: 
    name: "Vodafone (Japan - Toukai)"
    value: "@h.vodafone.ne.jp"
  vodafone-spain: 
    name: "Vodafone (Japan - Spain)"
    value: "@vodafone.es"
  vodafone-uk: 
    name: "Vodafone (UK)"
    value: "@sms.vodafone.net"
config: 
  from_address: noreply@hipscan.com
