:restaurant:
  :logo:
    :field_name: 'Logo'
    :field_type: :file
  :phone_number:
    :field_name: 'Phone Number'
    :field_type: :string
    :size: '15'
    :validate_presence: :true
    :validate_phone: :true
  :about:
    :field_name: 'About'
    :field_type: :page
  :find_us:
    :field_name: 'Find Us'
    :field_type: :url
    :title: 'Enter URL for Google Map directions'
    :size: '80'
  :hours:
    :field_name: 'Hours of Operation'
    :field_type: :page
  :delivery:
    :field_name: 'Food Delivery'
    :field_type: :page
  :menu:
    :field_name: 'Menu'
    :field_type: :string
  :website:
    :field_name: 'Full Website'
    :field_type: :url
    :title: 'Enter URL for Website'
    :size: '80'
  :facebook:
    :field_name: 'Facebook'
    :field_type: :url
    :title: 'Enter URL for Facebook'
    :size: '80'
  :twitter:
    :field_name: 'Twitter'
    :field_type: :url
    :title: 'Enter URL for Twitter'
    :size: '80'
  :specials:
    :field_name: 'Current Specials'
    :field_type: :page
  :footer:
    :field_name: 'Footer'
    :field_type: :string
    :size: '60'
    :validate_presence: :true
    :validate_phone: :true
:real_estate:
  :logo:
    :field_name: 'Logo'
    :field_type: :file
  :welcome_title:
    :field_name: 'Welcome title'
    :field_type: :string
  :agent_detail:
    :field_name: 'Agent Detail'
    :field_type: :page
  :agent_listing:
    :field_name: 'Agent Listing'
    :field_type: :page
  :agent_detail:
    :field_name: 'Contact'
    :field_type: :page
  :detail_page:
    :field_name: 'Detail Page'
    :field_type: :page
  