:restaurant:
  :logo:
    :field_name: 'Logo'
    :field_type: :file
  :phone_number:
    :field_name: 'Phone Number'
    :field_type: :string
    :size: '15'
    :validate_presence: :true
    :validate_phone: :true
  :about:
    :field_name: 'About'
    :field_type: :page_content
    :content:
      :about:
        :field_name: 'About'
        :field_type: :page
  :find_us:
    :field_name: 'Find Us'
    :field_type: :page_content
    :content:
      :address:
        :field_name: 'Address'
        :field_type: :string
        :title: 'Enter your address'
        :size: '80'
      :address2:
        :field_name: 'Address 2'
        :field_type: :string
        :title: 'Enter your address 2'
        :size: '80'
      :city:
        :field_name: 'City'
        :field_type: :string
        :title: 'Enter your City'
        :size: '80'
      :zip:
        :field_name: 'Zip Code'
        :field_type: :string
        :title: 'Enter your Zip code'
        :size: '80'
      :country:
        :field_name: 'Country'
        :field_type: :string
        :title: 'Enter your Country'
  :hours:
    :field_name: 'Opening Hours'
    :field_type: :page_content
    :content:
      :hours:
        :field_name: 'Hours of Operation'
        :field_type: :page
  :delivery:
    :field_name: 'Delivery Information'
    :field_type: :page_content
    :content:
      :delivery:
        :field_name: 'Food Delivery'
        :field_type: :page
  :menu:
    :field_name: 'Menu'
    :field_type: :page_content
    :content:
      :menu:
        :field_name: 'Menu'
        :field_type: :page
  :website:
    :field_name: 'Full Website'
    :field_type: :url
    :title: 'Enter URL for Website'
    :size: '80'
  :facebook:
    :field_name: 'Facebook'
    :field_type: :url
    :title: 'Enter URL for Facebook'
    :size: '80'
  :twitter:
    :field_name: 'Twitter'
    :field_type: :url
    :title: 'Enter URL for Twitter'
    :size: '80'
  :specials:
    :field_name: 'Specials'
    :field_type: :page_content
    :content:
      :specials:
        :field_name: 'Current Specials'
        :field_type: :page
  :footer:
    :field_name: 'Footer'
    :field_type: :string
    :size: '60'
    :validate_presence: :true
    :validate_phone: :true
:real_estate:
  :logo:
    :field_name: 'Logo'
    :field_type: :file
  :welcome_title:
    :field_name: 'Main Message title'
    :field_type: :string
  :profile_photo:
    :field_name: 'Landing Page Photo (optional)'
    :field_type: :file
  :next_page:
    :field_name: 'Invitation to next page'
    :field_type: :string
  :agent_detail:
    :field_name: 'Consultant/Agent Detail'
    :field_type: :page_content
    :content:
      :name:
        :field_name: 'Full name'
        :field_type: :string
        :size: '100'
      :photo:
        :field_name: 'Profile Photo'
        :field_type: :file
      :title:
        :field_name: 'Title'
        :field_type: :string
        :size: '100'
      :email:
        :field_name: 'E-mail'
        :field_type: :string
        :size: '100'
      :phone_number:
        :field_name: 'Phone Number'
        :field_type: :string
        :size: '100'
      :phone_mobile_number:
        :field_name: 'Mobile Number'
        :field_type: :string
        :size: '100'
      :specialties:  
        :field_name: 'Specialties'
        :field_type: :string
        :size: '100'
      :office_address:  
        :field_name: 'Office Address'
        :field_type: :string
        :size: '100'
  :agent_listing:
    :field_name: 'Consultant/Agent Information/Listing Page'
    :field_type: :page_content
    :content:
      :photo_1:
        :field_name: 'Photo 1'
        :field_type: :file
      :title_1:
        :field_name: 'Listing title 1'
        :field_type: :string      
      :description_1:
        :field_name: 'Listing description 1'
        :field_type: :page
      :price_1:
        :field_name: 'Price 1'
        :field_type: :string
        :size: '100'
      :street_1:
        :field_name: 'Street Address 1'
        :field_type: :page
        :size: '300'
      :photo_2:
        :field_name: 'Photo 2'
        :field_type: :file
      :title_2:
        :field_name: 'Listing title 2'
        :field_type: :string      
      :description_2:
        :field_name: 'Listing description 2'
        :field_type: :page
      :price_2:
        :field_name: 'Price 2'
        :field_type: :string
        :size: '100'
      :street_2:
        :field_name: 'Street Address 2'
        :field_type: :page
        :size: '300'
  # :contact:
  #   :field_name: 'Contact'
  #   :field_type: :page_content
  # :detail_page:
  #   :field_name: 'Detail Page'
  #   :field_type: :page_content
:coupon:
  :logo:
    :field_name: 'Logo'
    :field_type: :file
  :welcome_title:
    :field_name: 'Main Message'
    :field_type: :string
  :fill_form: 
    :field_name: 'Form fill out instructions'
    :field_type: :string
  :copyright:
    :field_name: 'Copyright information'
    :field_type: :string
  :offer:
    :field_name: 'Offer'
    :field_type: :page_content
    :content:
      :welcome_title:
        :field_name: 'Welcome title'
        :field_type: :string
      :offer_title:
        :field_name: 'Coupon title'
        :field_type: :string
      :coupon_code:
        :field_name: 'Coupon code'
        :field_type: :string
      :coupon_description:
        :field_name: 'Description'
        :field_type: :page
      :facebook:
        :field_name: 'Facebook URL'
        :field_type: :string
        :title: 'Enter URL for Facebook'
      :twitter:
        :field_name: 'Twitter URL'
        :field_type: :string
        :title: 'Enter URL for Twitter'
      :youtube:
        :field_name: 'YouTube URL'
        :field_type: :string
        :title: 'Enter URL for You Tube'
      :phone_number:
        :field_name: 'Phone Number'
        :field_type: :string
      :email:
        :field_name: 'Email'
        :field_type: :string
      :website:
        :field_name: 'Website URL'
        :field_type: :url
        :title: 'Enter URL for Website'